sonar.projectKey=bharathcy_two_tire_application
sonar.projectName=Two-Tier DevOps Profile (Flask)
sonar.organization=bharathcy

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.exclusions=**/*.md,.github/**,Dockerfile,.dockerignore,**/static/**
